php-translation/symfony-bundle

- Catalogue/CatalogueManager.php
- Command/DeleteObsoleteCommand.php
- Command/ExtractCommand.php
- Service/ConfigurationManager.php
> Adding command for deleting obsolete messages

- Catalogue/CatalogueManager.php
- Catalogue/Operation/MetadataAwareMerge.php
- EditInPlace/Activator.php
- EditInPlace/ResponseListener.php
- EditInPlace/Translator.php
- EventListener/AutoAddMissingTranslations.php
- Model/CatalogueMessage.php
- Model/EditInPlaceMessage.php
- Model/SfProfilerMessage.php
- Model/WebUiMessage.php
- Service/CatalogueFetcher.php
- Service/Importer.php
- Storage/FileStorage.php
- Translator/FallbackTranslator.php
> Make classes final

- Command/DeleteObsoleteCommand.php
- Command/ExtractCommand.php
- Controller/WebUIController.php
- DependencyInjection/TranslationExtension.php
- Model/Configuration.php
- Resources/config/services.yml
- Service/ConfigurationManager.php
> Added configuration object

- DependencyInjection/Configuration.php
- DependencyInjection/TranslationExtension.php
- Service/ConfigurationManager.php
- Tests/Functional/BaseTestCase.php
- Tests/Functional/BundleInitializationTest.php
- Tests/Functional/EditInPlaceTest.php
- Tests/Functional/app/AppKernel.php
- Tests/Unit/Model/ConfigurationTest.php
> Tests and bugfixes

- Controller/EditInPlaceController.php
- Model/EditInPlaceMessage.php
The `SfProfilerMessage` has a similar convert method.
> Minor cleanup

- EditInPlace/Activator.php
> Bugfix. We should use "get" instead of has two times

- EventListener/EditInPlaceResponseListener.php
- Resources/config/edit_in_place.yml
- Translator/EditInPlaceTranslator.php
- Twig/TranslationExtension.php
> Removed feature folder

- Controller/SymfonyProfilerController.php
> Make sure we have a data collector

- Changelog.md
- composer.json
> Prepare for 0.3.0

- Controller/EditInPlaceController.php
Without this patch edit_in_place failed in Symfony 3.2
> Added translation cache dir

- Tests/Functional/EditInPlaceTest.php
- Tests/Functional/app/config/disabled_label.yml
@Nyholm added a test related to #89
> Add test on showing original "Edit in place" value

- Model/SfProfilerMessage.php
> Bugfix with Symfony 3.3 and ClonerData

- Catalogue/Operation/MetadataAwareMerge.php
- Controller/WebUIController.php
- DependencyInjection/CompilerPass/StoragePass.php
- DependencyInjection/CompilerPass/ValidatorVisitorPass.php
- DependencyInjection/TranslationExtension.php
- Resources/config/extractors.yml
- Service/StorageService.php
- TranslationBundle.php
- composer.json
With these extractors we extract everything JMS translator does and more!
> Adding more extractors

- Catalogue/CatalogueCounter.php
- Catalogue/CatalogueManager.php
- Catalogue/MetadataWriter.php
- Catalogue/NoteParser.php
- Command/ExtractCommand.php
- Resources/config/services.yml
- Service/Importer.php
Sorry for a messy PR. This PR does also refactor `NoteParser` and`MetadataWriter`.
NoteParser is needed to get structured data from a XML note. The MetadataWriter writes metadata (like notes) to the Catalogue. It makes sure we do not have duplicates. 
The `CatalogueCounter` could be used for #52
> Adding status after extract command

- Resources/config/extractors.yml
To make sure we rewrite paths and stuff properly in https://github.com/php-translation/cli
> Make the Bundle compatible with the CLI

- Catalogue/MetadataWriter.php
- Catalogue/NoteParser.php
- Command/ExtractCommand.php
- Model/ImportResult.php
- Service/Importer.php
Note, this is a breaking change
Related to #116
> Add ImportResult model as suggested in #116

- Command/StatusCommand.php
- Resources/config/extractors.yml
> Adding status command

- .travis.yml
- Resources/config/extractors.yml
- Tests/Functional/BundleInitializationTest.php
- Twig/DummyTwigVisitor.php
- composer.json
> Added more test,

- Resources/config/services.yml
> Add Loader and Dumper from symfony storage

- Controller/WebUIController.php
- DependencyInjection/Configuration.php
- DependencyInjection/TranslationExtension.php
- Resources/views/WebUI/show.html.twig
This is needed for the CLI. The "full_path" was removed when redoing the metadata
> Adding base path to messages in WebUI.

- Resources/public/js/symfonyProfiler.js
Correct JS to make work "Synchronize all translations"
More details: https://github.com/php-translation/symfony-bundle/issues/154
> Correct JS

- Changelog.md
> Prepare for 0.5.0

- DependencyInjection/TranslationExtension.php
- Resources/config/console.yml
> Register the commands as services.

- DependencyInjection/TranslationExtension.php
> Make sure one can dump configuration

- Changelog.md
- composer.json
> Prepare for 0.6.0

- Model/Metadata.php
- Tests/Unit/Catalogue/CatalogueManagerTest.php
> Code clean up

- DependencyInjection/TranslationExtension.php
- Resources/config/edit_in_place.yml
> Fixed Edit in place twig extension activator

- .travis.yml
Running phpunit with code coverage is super slow.
> Increase max execution time

- Model/Metadata.php
- Service/Importer.php
> Add support for adding translation on SourceLocation

- Changelog.md
> Prepae for release 0.7.0

- Translator/FallbackTranslator.php
This makes us extra sure that we actually have a locale
> Make sure we got a locale before we start to translate

- Resources/config/routing_edit_in_place.yml
- Resources/config/routing_symfony_profiler.yml
- Resources/config/routing_webui.yml
User Deprecated: Referencing controllers
> Deprecated in Symfony 4.1

- composer.json
No changes were made in these libraries
> Support stable version for php-translation packages

- Resources/public/js/webui.js
- Resources/views/WebUI/show.html.twig
Hi !
This is my first contribution.
I would like to propose this feature. 
This add 2 filters in webui for filter empty messages only and restore all messages.
> New Feature add Filters in webui

- Command/SyncCommand.php
Just more info when using `--help`
> Add "up" to available direction in sync command

- Command/StatusCommand.php
Minor updates to the argument descriptions.
> Update StatusCommand argument descriptions

- Readme.md
Upgrade docs according to Symfony 4 structure and sync code examples with the recipe.
> Update docs in README according to Symfony 4

- Tests/Unit/Twig/BaseTwigTestCase.php
- composer.json
We want to support latest Twig versions. 
Also, there is no reason why we should support twig versions from years back, right?
> Bump Twig versions

- Changelog.md
> Added change log for 0.9.0

- Catalogue/Operation/ReplaceOperation.php
- Changelog.md
- Tests/Unit/Catalogue/Operation/ReplaceOperationTest.php
Hm... I missed this. That class is complicated..
> Bug fix replace operation with null values

- .gitattributes
- .github/workflows/static.yml
- phpstan.neon.dist
Adding only PHPStan as requested by @rvanlaak
> Adding PHPStan

- DependencyInjection/Configuration.php
Application of @SinSquare proposal in #231
> [Config] Allow user to use custom dumper (#231)

- Command/DeleteObsoleteCommand.php
- Command/DownloadCommand.php
- Command/ExtractCommand.php
- Command/StatusCommand.php
- Command/SyncCommand.php
All commands must return an integer.
See https://github.com/symfony/symfony/pull/33775
> Commands should always return int

- Tests/Functional/app/config/framework.yml
- composer.json
Remove dev dependency on a deprecated component
> Remove symfony/templating dependency

- Resources/config/auto_translation.yaml
The `php_translator.fallback_translator` service has a new id.
> Bugfix with service names

- Resources/views/SymfonyProfiler/edit.html.twig
Fix #384 
Dark mode:
Light mode:
> Improve rendering to support dark mode

- Resources/public/js/editInPlace.js
- Resources/public/js/webui.js
> Always send X-Requested-With header when making an AJAX call

- Changelog.md
https://github.com/php-translation/symfony-bundle/pull/386
https://github.com/php-translation/symfony-bundle/pull/387
> Prepare 0.11.2 release

- Changelog.md
There is no need to make the release now, but I'm just adding changelog.
> Added changelog for 0.11.3

- Changelog.md
Merged PRs:
- https://github.com/php-translation/symfony-bundle/pull/395
- https://github.com/php-translation/symfony-bundle/pull/403
> Prepare 0.12 release

- Tests/Functional/app/config/framework.yaml
Hi,
This tiny PR will fix : 
- 1 typo in `Tests/Functional/app/config/framework.yaml`
Bye! :robot:
> Fix typo in Tests/Functional/app/config/framework.yaml

- Controller/WebUIController.php
> Fixed small typo

- .github/workflows/ci.yml
- composer.json
It has reached EOL a long time ago
> Drop Symfony 3

- Tests/Functional/app/config/framework.yaml
- composer.json
- phpstan.neon.dist
> Fix tests on Symfony 5.3

- Resources/config/extractors.yaml
> register visitor tag also for TranslateAnnotationVisitor and Knp visitors

- Resources/config/symfony_profiler.yaml
To simplify config, suggested idea by @rvanlaak here: https://github.com/php-translation/symfony-bundle/pull/460#discussion_r789603130
> Use autowiring for SymfonyProfilerController

- Resources/config/auto_add.yaml
- Resources/config/auto_translation.yaml
- Resources/config/console.yaml
- Resources/config/edit_in_place.yaml
- Resources/config/routing_symfony_profiler.yaml
- Resources/config/routing_webui.yaml
- Resources/config/services.yaml
- Resources/config/symfony_profiler.yaml
I think it's time to fix indentation finally, there was a mix of it so far
> Fix yaml indentation to 4 spaces

- Changelog.md
The draft release: https://github.com/php-translation/symfony-bundle/releases/tag/untagged-b2d4a3f294078e788859
> Prepare 0.12.6

- Catalogue/Operation/ReplaceOperation.php
- Tests/Functional/Controller/WebUIControllerTest.php
> Fix code styles

- Changelog.md
As requested in https://github.com/php-translation/symfony-bundle/issues/484
> Prepare 0.12.8

- composer.json
> Allow Composer to run php-http/discovery plugin

- Command/CheckMissingCommand.php
- Command/DeleteEmptyCommand.php
- Command/DeleteObsoleteCommand.php
- Command/ExtractCommand.php
- Command/StorageTrait.php
- Command/SyncCommand.php
- Controller/SymfonyProfilerController.php
- Controller/WebUIController.php
- DependencyInjection/CompilerPass/StoragePass.php
- DependencyInjection/Configuration.php
- DependencyInjection/TranslationExtension.php
- EventListener/EditInPlaceResponseListener.php
- Service/CacheClearer.php
- Service/ConfigurationManager.php
- Service/Importer.php
- Service/StorageService.php
- Translator/EditInPlaceTranslator.php
- Translator/FallbackTranslator.php
- Twig/Node/Transchoice.php
> Fix CS w/ PHP CS Fixer

- Command/CheckMissingCommand.php
- Command/DeleteEmptyCommand.php
- Command/DeleteObsoleteCommand.php
- Command/DownloadCommand.php
- Command/ExtractCommand.php
- Command/StatusCommand.php
- Controller/WebUIController.php
- Service/Importer.php
- Tests/Functional/app/Service/DummyMessageFactory.php
> refac: fix cs

- .github/workflows/ci.yml
- .github/workflows/static.yml
- Readme.md
* add badges to readme for ci & static analysis status
* github workflow
* restrict pull_request only for master
* add push event
> feat: add CI & static analysis badges
