php-translation/symfony-bundle

Controller/WebUIController.php, Exception/MessageValidationException.php, Model/GuiMessageRepresentation.php
Fixed issue #6 
I did not use the serializer component for two reasons. 
1) I try to keep the dependencies to a minimum. 
2) It would require us to add normalizers to the serializer. Configuring the serializer service would be more lines than the current use case. 
This PR is using proper validation though.
=> Added validation for the ajax requests

.travis.yml
=> Test with symfony 3.2 and not 3.0

DependencyInjection/Configuration.php, DependencyInjection/TranslationExtension.php, EventListener/AutoAddMissingTranslations.php, Resources/config/auto_add.yml, Service/StorageService.php, composer.json
This will add all missing translations to the storage. 
This will fix #20
=> Added auto adder feature

Controller/WebUIController.php, Resources/public/css/webui.css, Resources/public/js/webui.js, Resources/views/WebUI/create.html.twig, Resources/views/WebUI/index.html.twig, Resources/views/WebUI/show.html.twig, Service/CatalogueFetcher.php
This will fix #1, related to #27
=> Allow to add and delete messages in web ui

Controller/EditInPlaceController.php
This is a proposal for cache clearing after translation editing. As the Edit In Place functionality is supposed to be used "live", it was looking "broken" because even if a translation is edited correctly, Symfony still display the old messages until the cache is cleared.
I can't think of any better solution but I do not like this very much, editing the cache directory seems like a hack... :confused: 
II tried another approach: doing a `touch()` on the translation files and calling the warmer, but Symfony Cache implementation for translations don't have any resourceCheckers so it can't work. We have to remove the file for them to be rewritten.
About the `name('*.'.$locale.'.*')` pattern, I checked and it's compatible with Symfony 2.7 and more.
Ref #63
=> Clear the translations cache after editing with Edit In Place

EventListener/EditInPlaceResponseListener.php, Tests/Functional/EditInPlaceTest.php, Tests/Functional/app/Resources/views/translated.html.twig
- fixes issue where everything was removed between two translations of html attribute contents on the same line
- fixed issue when translation used in special link with additional content in href attribute: `<a href="email:*localizedEmail*">`
=> fixed attribution replacement

DependencyInjection/TranslationExtension.php, Resources/config/extractors.yml
makes use of php-translation/extractor twig2 support
=> twig2 compatibility

Resources/views/WebUI/show.html.twig
Just replaced "email" by "text" in WebUI show view.
=> Web UI translate input field set as email

Resources/views/SymfonyProfiler/edit.html.twig
Right now the profiler textarea is too small, made it use the full width.
=> Let profiler textarea use full available width

DependencyInjection/Configuration.php, DependencyInjection/TranslationExtension.php, EventListener/EditInPlaceResponseListener.php, Resources/config/edit_in_place.yml, Translator/EditInPlaceTranslator.php
Introduce a new configuration option below `edit_in_place` to not show the "untranslatable" label, but show the original content instead. Translators then still can do the translation via the profiler or webUI integration. See #66 
```yml
translation:
edit_in_place:
show_untranslatable: false # default = true
```
This PR also is a preparation for #87 in order to not replace the parameters via "edit in place", as the `<x-trans>` tags now also include the original and plain translation.
/cc @damienalexandre
=> Add configuration option to not show "untranslatable"

DependencyInjection/CompilerPass/SymfonyProfilerPass.php, Resources/config/symfony_profiler.yml, TranslationBundle.php
If you are trying to use the Symfony Profiler and the SymfonyTranslation is not enabled, we should fail with an exception.
=> Make sure we fail with an exception if SfTranslation is not enabled.

Controller/SymfonyProfilerController.php, Resources/config/routing_symfony_profiler.yml
Ref #95 
Since this commit (https://github.com/symfony/translation/commit/79fe2b4039e0bac60fb28adaa9bc1f61730b8601#diff-d6cd38dc7a79e5153bf5a542aae85c4bR48) getMessages returns a Data object and not an array anymore.
---
*Quick-fix*: I've updated routing_symfony_profiler.yml because `createAssets` seems to me as never having been followed ^^' (ping @damienalexandre)
=> Fix type of data returned by translation data collector since sf 3.3

Changelog.md, Readme.md
=> Add changelog for 0.3.2

.travis.yml, Changelog.md, Model/SfProfilerMessage.php
See https://github.com/php-translation/loco-adapter/pull/7 and https://github.com/FriendsOfApi/localise.biz/pull/16.
This PR adds Meta informations from the Data Collector Message to the Common Message object. This allow the Loco-Adapter to use this Meta information in order to add the parameters as notes on newly created assets.
=> Add Meta Informations to the common Message object

Resources/config/edit_in_place.yml, Twig/TranslationExtension.php, composer.json
This will fix #100 and replace #101
=> Do only not escape twit filter output when EditInPlace is false

Changelog.md, Tests/Functional/EditInPlaceTest.php, Twig/TranslationExtension.php
... as now output is marked as safe when `EditInPlace` is inactive. Should be the other way around.
=> Switch activator comparison result

Changelog.md, Resources/public/css/images/loader.svg, Resources/public/js/symfonyProfiler.js, Resources/views/SymfonyProfiler/translation.html.twig
I've added some cool UI features to improve usability in Profiler. ✌️
Enjoy ! 🎉
=> Improve UI/UX in Profiler

DependencyInjection/CompilerPass/SymfonyProfilerPass.php, DependencyInjection/Configuration.php, Tests/Unit/DependencyInjection/TranslationExtensionTest.php, composer.json
Symfony profiler integration default value changed to "same as debug mode".
We do not longer throw exception when Symfony Translation collector was not found.
This will fix #107 
Ping @aradoje
=> Do not throw exception when SF Translation collector is not found. 

Changelog.md
=> Prepare for 0.4.0

Changelog.md, Command/DownloadCommand.php, Controller/EditInPlaceController.php, Resources/config/services.yml, Service/CacheClearer.php
This new feature allow to clear the local Symfony Cache when we detect a change in the downloaded translations.
It's already used today in production and I'm very please with it, so I think it belong here.
The idea is that you can run this command in a crontab, and when a translation is changed on the remote (SaaS translations like Loco), we can clear the Symfony cache if we detect that you have changed the translations => **instant translation update on productions** :tada:
=> Add a --cache option on translation:download to clear the cache

Controller/SymfonyProfilerController.php, Controller/WebUIController.php
`:` way to call views is not supported anymore for Twig 2.x branch.
My fix is tested for an app with Twig 2.4, but not with Twig 1.x. But, as [Twig documentation explain](https://twig.symfony.com/doc/1.x/api.html#loaders) `@` namespace are supported.
Let me know for any improvement if necessary ;)
=> Fix twig paths for Twig 2.x

Readme.md
It's defacto standard, easy to copy/paste to existent projects, you don't need to re-indent pasted code
=> Tweak indentations to 4 spaces as in Symfony recipes

DependencyInjection/Configuration.php, Resources/config/auto_translation.yml
I see Translator already supports Yandex: https://github.com/php-translation/translator/pull/7
=> Add Yandex translator support

Controller/SymfonyProfilerController.php
I solved this error by using message key from query parameter instead of current locale wich are different in case of the fallback translation, contrary to normal edition.
https://github.com/php-translation/symfony-bundle/issues/157
=> Correct translation fallback edition

Controller/WebUIController.php
By removing empty messages in the progress counter, so it gives a more realistic overview of the progress counter in the webui
=> Removing empty messages in the total count in webui, gives a better progress

Readme.md, Resources/views/WebUI/index.html.twig, Resources/views/WebUI/show.html.twig
Possible fix for templates in symfony 4
Fixes #168
=> Fix for symfony 4 templates

EventListener/EditInPlaceResponseListener.php
We use a decorated router in our project that causes problems when depending on the concrete symfony router.
=> depend on router interface instead of concrete implementation

Resources/config/edit_in_place.yml
The `php_translation.edit_in_place.activator` service should be public to make the instructions from http://php-translation.readthedocs.io/en/latest/symfony/edit-in-place.html work
=> Make activator service public

Command/BundleTrait.php, Command/DeleteObsoleteCommand.php, Command/DownloadCommand.php, Command/ExtractCommand.php, Command/StatusCommand.php, Command/SyncCommand.php, Controller/EditInPlaceController.php, Controller/WebUIController.php, DependencyInjection/TranslationExtension.php, Resources/config/console.yml, Resources/config/services.yml, Service/StorageManager.php, Tests/Functional/Command/ExtractCommandTest.php, Tests/Functional/Command/StatusCommandTest.php
Inject all dependencies to commands. We should not rely on public services
This will add a StorageManager (similar to the ConfigurationManager). The storage manager handles all StorageServices
=> Inject depedencies to the commands

Controller/EditInPlaceController.php, Controller/SymfonyProfilerController.php, Controller/WebUIController.php, Model/SfProfilerMessage.php, Service/StorageService.php, composer.json
Blocked by https://github.com/php-translation/common/pull/20
=> Using MessageInterface

DependencyInjection/TranslationExtension.php
We already check that it's an array in the configuration definition.
This wraps the option array in another array, so the argument passed in the storage is "double wrapped" and cannot be properly used.
https://github.com/php-translation/symfony-storage/blob/e4446fe5243f5380df865d763564b28498b209ef/src/FileStorage.php#L60-L79
=> Remove useless array wrapping

composer.json
The extractor already require twig/twig. We are referencing `@twig` [here](https://github.com/php-translation/symfony-bundle/blob/master/Resources/config/extractors.yml#L9) and [here](https://github.com/php-translation/symfony-bundle/blob/master/Resources/config/services.yml#L35)
Is it wrong of us to require the bundle?
=> Require TwigBundle

.travis.yml, Catalogue/CatalogueFetcher.php, composer.json
This will fix #186. 
Using NSA is a hack.. There is no other way to do it... I cannot find any however.
=> Better respect blacklist and whitelist

DependencyInjection/CompilerPass/FileDumperBackupPass.php, Resources/config/services.yml, TranslationBundle.php
Heya :wave: 
This PR should fix the deprecation notices for https://github.com/symfony/translation/blob/4.1/Dumper/FileDumper.php#L52 
If you have any additions or changes I'd love to know.
=> Fix the FileDumper::setBackup() method deprecation notice

Command/DeleteObsoleteCommand.php, Command/DownloadCommand.php, Command/StorageTrait.php, Command/SyncCommand.php, Tests/Functional/Command/SyncCommandTest.php
Avoid weird errors like `Call to a member function sync() on null` for example.
=> Ensure storage exists before using it in commands

Resources/config/services.yml, Service/Importer.php
=> Only add value from `@desc` if catalogue has the default locale

Resources/views/WebUI/show.html.twig
It wasn't showing on all devices.
I replaced it by the one of the [Boostrap documentation](https://getbootstrap.com/docs/4.1/utilities/close-icon/)
=> Replace unicode close icon by the Bootstrap Icon

Tests/Unit/Translator/EditInPlaceTranslatorTest.php, Translator/EditInPlaceTranslator.php
An error could occur when using Edit In Place with HTML in the translations:
```
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': 'show-for-custom-md"' is not a valid attribute name.
at c.mount (http://notarealwebsite.com:8000/bundles/translation/js/content-tools.min.js?9:3:20706)
at new c (http://notarealwebsite.com:8000/bundles/translation/js/content-tools.min.js?9:3:12341)
at c._initRegions (http://notarealwebsite.com:8000/bundles/translation/js/content-tools.min.js?9:6:24008)
at c.start (http://notarealwebsite.com:8000/bundles/translation/js/content-tools.min.js?9:6:20300)
at b.<anonymous> (http://notarealwebsite.com:8000/bundles/translation/js/content-tools.min.js?9:6:14355)
at b.a.dispatchEvent (http://notarealwebsite.com:8000/bundles/translation/js/content-tools …
```
=> [EditInPlace] Fix bad HTML generation when there is HTML in the translation

Resources/views/SymfonyProfiler/translation.html.twig
The block name change from panelContent to panel
=> Fix compatibility with Symfony 4.3

.travis.yml, Controller/WebUIController.php, Tests/Unit/Twig/BaseTwigTestCase.php, composer.json, phpunit.xml.dist
The current version of this bundle does not work with Symfony 4.2 well due to the new Intl formatter, that's why some tests failed. Other tests failed due to BC breaks and deprecations. Probably we should downgrade Sf Translation component version to `<4.2` before a proper fix to avoid BC breaks. Also, let's do not force failing builds on deprecation notices since this bundle is not actively developed lately - it causes more problems. Also, not sure, but it seems like TravisCI just dropped PHP 5.5 support, so I had to use PHP 5.6 as lowest PHP version
=> An attempt to make all tests green again so we can moving forward and merge PRs

Command/DeleteObsoleteCommand.php, Command/DownloadCommand.php, DependencyInjection/Configuration.php, Resources/config/auto_translation.yml
Looks like we have Bing translator.
=> Add missing Bing translator

Command/DeleteObsoleteCommand.php
Fixes the translationdelete-obsolete command not running in non-interactive shells. The question was simply never asked, not even when using 'yes'. This fix will run the command (assume yes) on non-interactive shells which allows you to run the command in scripts (e.g. update a lot of translations).
=> Fix delete obsolete translations command on non-interactive cli

EventListener/EditInPlaceResponseListener.php
I encountered an error with the EditInPlaceListener, when you try to return a BinaryResponse, a test is done to check if the content is null, if not, it throw an error.
But with the EditInPlace enabled, the content is always changed to an empty string, then it fail: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L315
I just add a test to check if the ->getContent return false, in this case we return and abort the edit in place listener action.
=> [EditInPlaceListener] Test if response content is false

Resources/public/js/editInPlace.js
`document.registerElement()` doesn't exist anymore at least in Firefox. According to [MDN Documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement), it has been replaced by [`customElements.define()`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define).
Close #270
=> [Js] Fix registering custom elements

.travis.yml, Changelog.md, composer.json, phpunit.xml.dist
Minior thing to make the build green
=> Bump to Symfony 3.4 and PHP 7.1

Resources/config/extractors.yml, composer.json
The FormTypeHelp extractor (https://github.com/php-translation/extractor/pull/113) was not tagged as visitor, so was not used when launching **translation:extract** command.
=> Tagged FormTypeHelp extractor

Resources/views/WebUI/base.html.twig, Resources/views/WebUI/index.html.twig, Resources/views/WebUI/show.html.twig
Changed the block names, so its not using the "default" ones, so its much easier to overwrite the base template, so it can be fitted into your own admin view.
So you doesnt need to overwrite 3 templates, but can overwrite just the base template
=> WebUI - Template block names

Service/Importer.php, Tests/Unit/Twig/BaseTwigTestCase.php, Twig/EditInPlaceExtension.php, Twig/Node/Transchoice.php, Twig/TranslationExtension.php, Twig/Visitor/DefaultApplyingNodeVisitor.php, Twig/Visitor/NormalizingNodeVisitor.php, Twig/Visitor/RemovingNodeVisitor.php, composer.json
It's a following of https://github.com/php-translation/symfony-bundle/issues/288#issuecomment-472081268, since Twig 3 will remove non-namespaced classes.
---
EDIT: hum, there is a lot of Travis builds that fail: 
- either because Composer ran out of memory (see #291)
- either because deprecations make PHPUnit exit with status code different of 0, 
- either because they are failing tests with `new_c` and `old_d` (which appears on other PRs too) :(
=> chore(twig): replace class aliases by class namespaces

composer.json
Let's see if tests pass, but most probably will need to fix some things to make them green with this change
=> Try to allow any Twig version

Catalogue/Operation/ReplaceOperation.php, composer.json
This will replace #323 and fix #321
I basically rewrote and simplified ReplaceOperation.
=> Support for all Symfony translation versions

composer.json
Im not sure why we limited the versions in #313. But removing a direct dependency in #324 is not a good solution. 
I've added back `twig/twig` with their latest 1.x and 2.x versions.
=> Added twig as a dependency

Resources/views/SymfonyProfiler/translation.html.twig, Resources/views/WebUI/show.html.twig
Since Twig 2.7, `{% spaceless %}` is deprecated, and will be removed in Twig 3.0.  This PR replaces it with `{% apply %}`. The result is one less deprecation notice. 
This PR also replaces the deprecated `{% for … if … %}` with `|filter(…)`.
See: https://twig.symfony.com/doc/2.x/deprecated.html
=> Replace (deprecated) `{% spaceless %}` and `{% for … if … %}` in Twig

DependencyInjection/TranslationExtension.php, Resources/config/edit_in_place.yml, Twig/EditInPlaceExtension.php
The `TranslationExtension` have been marked as final (see https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php#L29).
Use encapsulation instead of inheritance + clean service declaration.
:warning: This introduce a BC Break as methods `setRequestStack` & `setActivator` have been removed.
If those methods were there on purpose, I can add them back.
=> Do not extends extension marked as final

.gitignore, Command/DeleteObsoleteCommand.php, Command/DownloadCommand.php, Command/ExtractCommand.php, Command/StatusCommand.php, Service/ConfigurationManager.php, Tests/Unit/Service/ConfigurationManagerTest.php, TranslationBundle.php
Exception on missing configuration was only thrown when using a command. This fix that by moving Exception directly into `getConfiguration()` method which is also called in `WebUIController`
=> Move Exception into getConfiguration method

Model/SfProfilerMessage.php
`transChoiceNumber` can be null
See: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Translation/DataCollectorTranslator.php#L156
=> Correct incorrect return type

Resources/config/edit_in_place.yaml, Resources/config/webui.yaml
Lets be specific, there is no need to trust/hope that the user has configured the correct compiler passes.
=> Use specific tags instead of autoconfigure

Changelog.md
The [diff](https://github.com/php-translation/symfony-bundle/compare/0.9.1...master) is quite large, but there is not many breaking changes. =)
That feels great and I believe we are close to 1.0.
=> Prepare for 0.10.0

Resources/views/SymfonyProfiler/translation.html.twig
* Override only some blocs instead of overriding the whole panel.
* Show checkbox & button only on missing tab
Fix #295 #296 
Now looks like this:
=> Update Profiler view

Command/DownloadCommand.php, DependencyInjection/TranslationExtension.php, Resources/config/console.yaml, Resources/config/services.yaml, Service/StorageService.php
=> Improve download command

Service/StorageService.php, composer.json
=> Update symfony-storage requirement

composer.json, phpstan-baseline.neon
... and use branch alias if available via `minimum-req = dev`.
=> Prefer stable packages

Changelog.md, Controller/SymfonyProfilerController.php, phpstan-baseline.neon
It needed to be 0.11.0 instead of 0.10.1 since we changed the `StorageService::download()`.
=> Prepare release 0.11.0

DependencyInjection/TranslationExtension.php
When using environment variables as values for config parameters that are read conditionally, symfony can mark that environment variable as unused and throw a fatal error.
For example, the following config:
```
translation:
fallback_translation:
enabled: '%env(bool:FALLBACK_TRANSLATION_ENABLED)%'
```
Will result in a fatal error if the environment variable is not used elsewhere. `Environment variables "bool:FALLBACK_TRANSLATION_ENABLED" are never used. Please, check your container's configuration.`
This PR solves this issue, see https://github.com/symfony/symfony/issues/23520#issuecomment-336167214 and the comment below that.
=> Resolve environment placeholders

Catalogue/CatalogueManager.php, Command/ExtractCommand.php
This fixes the problem that catalogues are read from the "main" translation directory when extracting messages only for a specific bundle. The effect of this change is that messages from the main configuration are not entirely copied into the bundle being processed.
The second commit fixes another problem: when using the YAML format it may happen that the initial translation is `null` instead of an empty string. The `createMessage()` method expects a string argument though.
=> Configure bundle dir before fetching catalogues

Controller/WebUIController.php
This PR ensures that exception messages are returned with status code 400 so they are shown in the Web UI instead of `Unknown error.`.
It also replaces the `400` number by the corresponding `Response` constant.
=> catch exceptions when storing translations

Catalogue/CatalogueManager.php, Command/DeleteEmptyCommand.php, phpstan-baseline.neon
translation:extract on a new lang currently export keys with empty string as translation, resulting in empty string being valid translations.
I prefer to delete empty translations than having empty string, so fallback can be used
=> Add command to delete empty messages

Command/DownloadCommand.php, Command/SyncCommand.php, Service/StorageService.php
This will partly fix #326 
Are the names `import-conf`/`export-conf` good enough? Should they be replaced with `download/upload`? (export = download, since the function is on the StorageInterface, exporting from a storage is taking things out of it...)
=> Add support for arbitrary options to StorageInterface::export()/import()

DependencyInjection/TranslationExtension.php, Resources/config/extractors.yaml, phpstan-baseline.neon
This PR adds a service definition for the extractor wanted in https://github.com/php-translation/symfony-bundle/issues/394
Do not merge before https://github.com/php-translation/extractor/pull/148 is merged.
=> add service definition for form field title extractor

Command/CheckMissingCommand.php
This PR ensures that `translation:check-missing` does not break if a null value is given to the closure used in `countEmptyTranslations` method.
Error message:
```
In CheckMissingCommand.php line 137:
Argument 1 passed to Translation\Bundle\Command\CheckMissingCommand::Translation\Bundle\Command\{closure}() must be of the type string, null given
```
=> allow null values in CheckMissingCommand

Changelog.md, Resources/config/console.yaml
=> Prepare release 0.12.2

Resources/config/extractors.yaml
This change simplify future and repair error with unused var $metadatafactory in extractor.yaml
=> fix extractor parameters

Readme.md
First of all, the correct link should be https://insight.symfony.com/projects/c289ebe2-41c4-429f-afba-de2f905b9bdb - but there's no data, so probably better to remove the badge completely instead of showing failed badge for now
=> Drop SensioLabs (Symfony) insight badge

Controller/SymfonyProfilerController.php, Resources/config/symfony_profiler.yaml
Fixes #436
These changes allow us to keep the profiler feature enabled by default in the recipe: https://github.com/symfony/recipes-contrib/blob/ff7313b337a4c0ec894684f71b62240a31816e9f/php-translation/symfony-bundle/0.10/config/packages/dev/php_translation.yaml#L3 to have good discoverability of the feature for those who have the `symfony/web-profiler-bundle` installed but won't throw an exception if the `symfony/web-profiler-bundle ` is missing in the project on `composer require php-translation/symfony-bundle`. If somehow this feature will be tried to use - we will show a clear user-friendly message about requiring `symfony/web-profiler-bundle` dependency first.
=> Make Profiler service an optional argument for SymfonyProfilerController

Legacy/LegacyHelper.php, Translator/EditInPlaceTranslator.php, Twig/EditInPlaceExtension.php
Suppress this deprecation message:
> Since symfony/http-foundation 5.3: "Symfony\Component\HttpFoundation\RequestStack::getMasterRequest()" is deprecated, use "getMainRequest()" instead.
=> Suppress getMasterRequest() deprecation message

Tests/Functional/Command/ExtractCommandTest.php, Tests/Functional/Command/SyncCommandTest.php
> `assertRegExp()` is deprecated and will be removed in PHPUnit 10. Refactor your code to use `assertMatchesRegularExpression()` instead.
=> Fix PHPUnit deprecations

Changelog.md
=> Prepare release v0.12.4

Controller/EditInPlaceController.php
Fix deprecation
```
Since symfony/dependency-injection 5.1: The "Psr\Container\ContainerInterface" autowiring alias is deprecated. Define it explicitly in your app if you want to keep using it. It is being referenced by the "Translation\Bundle\Controller\EditInPlaceController" service.
```
related also to #455
=> refac: remove AbstractController from EditInPlaceController

EditInPlace/Activator.php, Resources/config/edit_in_place.yaml
This change is necessary to fix an error created by a removed deprecation.
deprecation:
https://symfony.com/blog/new-in-symfony-5-3-session-service-deprecation
=> Fix for deprecated session service in Symfony 6

Tests/Unit/Translator/EditInPlaceTranslatorTest.php, Translator/EditInPlaceTranslator.php, Translator/FallbackTranslator.php
Try to fix failed tests in #469
=> Fix return type and implement getCatalogues()

Command/ExtractCommand.php, Controller/SymfonyProfilerController.php
Closes #284 excluded_dirs in config matches filenames too
tested it with my project (exclude_dir "data"). My file "base_data" is now correctly extracted, while translations inside my "data" folder are ignored as expected.
Only possible issue I see is some users expecting "exclude_dirs" to also exclude filenames, which would be a bit weird as it's been marked as bug since 3 years.
Anyway, that could be easily fixed by simply adding the values of "excluded_dirs" to "excluded_names".
=> fix: used finder->exclude instead of notPath for excludedDirs

EditInPlace/Activator.php
In some requests no session is available.
I have this problem specifically when using cross domain requests in the preflight request. 
This gives an error in the activator for 'edit in place'. Checking if the session is available before executing the code solves the problem.
=> fix: check if session if available

EditInPlace/Activator.php, Model/SfProfilerMessage.php, Tests/Functional/BaseTestCase.php, Tests/Functional/BundleInitializationTest.php, Tests/Functional/Catalogue/CatalogueFetcherTest.php, Tests/Functional/Command/CheckMissingCommandTest.php, Tests/Functional/Command/ExtractCommandTest.php, Tests/Functional/Command/StatusCommandTest.php, Tests/Functional/Command/SyncCommandTest.php, Tests/Functional/Controller/EditInPlaceControllerTest.php, Tests/Functional/Controller/EditInPlaceTest.php, Tests/Functional/Controller/WebUIControllerTest.php, Tests/Functional/app/Service/DummyHttpClient.php, Tests/Functional/app/Service/DummyMessageFactory.php, Tests/Functional/app/config/default_legacy.yaml, Tests/Functional/app/config/disabled_label_legacy.yaml, Tests/Functional/app/config/framework.yaml, Tests/Functional/app/config/framework_legacy.yaml, composer.json, phpunit.xml.dist
The `nyholm/symfony-bundle-test` prevents to upgrade to Symfony 6 completely as `symfony/framework-bundle` because it's installed as 5.4 for the current version SymfonyBundleTest version, see installed deps here: https://github.com/php-translation/symfony-bundle/runs/8168054961?check_suite_focus=true
I tried to upgrade it to the v2.0 and fixed broken tests so that this bundle could use all Symfony 6 packages finally.
=> Upgrade the SymfonyBundleTest

Controller/SymfonyProfilerController.php
Symfony 6.x dropped support for request->get returning arrays. I am not using request->all($key) construction to maintain Symfony 4.4 compatibility.
=> Symfony Profiler Fix Symfony 6.x compatibility

.github/workflows/ci.yml, .github/workflows/static.yml, Catalogue/CatalogueManager.php, Catalogue/Operation/ReplaceOperation.php, Command/BundleTrait.php, Command/CheckMissingCommand.php, Command/DeleteEmptyCommand.php, Command/DeleteObsoleteCommand.php, Command/DownloadCommand.php, Command/ExtractCommand.php, Command/StatusCommand.php, Command/SyncCommand.php, Controller/WebUIController.php, DependencyInjection/Configuration.php, DependencyInjection/TranslationExtension.php, EditInPlace/Activator.php, Service/CacheClearer.php, Service/Importer.php, Translator/FallbackTranslator.php, Twig/EditInPlaceExtension.php, Twig/TranslationExtension.php, composer.json
- Remove symfony console $defaultName deprecation and use AsCommand annotation
- Upgrade to PHP ^8.0
- Upgrade to symfony ^5.3
Fix #490
=> Remove symfony console $defaultName deprecation

EventListener/AutoAddMissingTranslations.php, EventListener/EditInPlaceResponseListener.php, Resources/public/js/editInPlace.js
It seams that it is not allowed to use `HTMLElement` directly as constructor.
fix #409 
* remove old symfony 4 compatiblity layer (lib has min. 5.3 see composer.json)
* fix cs
=> bug: js error use own object extends HTMLElement

Resources/views/SymfonyProfiler/translation.html.twig
This fixes the issue described in #496
=> Fixed render error in profiler/translation.html.twig (fixes #496)

Resources/public/js/symfonyProfiler.js, Resources/views/SymfonyProfiler/edit.html.twig, Resources/views/SymfonyProfiler/translation.html.twig
Not sure exactly when it happened but in Symfony 6.4.1 the `Sfjs` class is not available in the profiler so i replaced `Sfjs.request` with `fetch`.
I wanted to change as little as possible so the requests match the old functionality and no controller changes are necessary.
Also included some minor styling adjustments to match the new profiler design and support dark-mode. Mainly avoiding the buttons to break in multiple lines and changing the font color in the textarea in dark-mode. Let me know if you would prefer a separate PR for those.
Before:
After:
Any feedback is welcome.
=> [SF PROFILER] Use fetch instead of Sfjs.request and minor style adjusments to better match the new profiler layout

.github/workflows/static.yml, Catalogue/CatalogueManager.php, Command/DeleteEmptyCommand.php, Command/DeleteObsoleteCommand.php, Service/Importer.php, composer.json, phpstan-baseline.neon
Should we also bump min PHP version in composer.json? I think it makes sense after #505 as we don't support 8.0 version in CI anymore
=> Bump PHP to 8.1 in composer.json

.github/workflows/ci.yml, .github/workflows/static.yml
fix github actions see #520
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
```
=> feat: use ubuntu-24.04 for github actions

Twig/Visitor/DefaultApplyingNodeVisitor.php, Twig/Visitor/NormalizingNodeVisitor.php, Twig/Visitor/RemovingNodeVisitor.php
Fix deprecation
```
1x: The "Translation\Bundle\Twig\Visitor\NormalizingNodeVisitor" class extends "Twig\NodeVisitor\AbstractNodeVisitor" that is deprecated since Twig 3.9 (to be removed in 4.0).
|     1x in CheckMissingCommandTest::testReportsMissingTranslations from Translation\Bundle\Tests\Functional\Command
| 
|   1x: The "Translation\Bundle\Twig\Visitor\RemovingNodeVisitor" class extends "Twig\NodeVisitor\AbstractNodeVisitor" that is deprecated since Twig 3.9 (to be removed in 4.0).
|     1x in CheckMissingCommandTest::testReportsMissingTranslations from Translation\Bundle\Tests\Functional\Command
| 
|   1x: The "Translation\Bundle\Twig\Visitor\DefaultApplyingNodeVisitor" class extends "Twig\NodeVisitor\AbstractNodeVisitor" that is deprecated since Twig 3.9 (to be removed in 4.0).
| …
```
=> refac: replace AbstractNodeVisitor with NodeVisitorInterface

Resources/public/js/editInPlace.js, Twig/Visitor/DefaultApplyingNodeVisitor.php
For HMR compatibility.  Fix the javascript error display in console and webpack error overlay : "Failed to execute 'define' on 'CustomElementRegistry': the name "x-trans" has already been used with this registry"
=> Webpack HMR compatibility: update editInPlace.js
